# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minwoo Ahn
title: Systems Software Researcher
email: mwahn402@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ski422
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

## Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
## - title: another link
##   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
##   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. candidate in the Department of Electrical and Computer Engineering at Sungkyunkwan University and also a member of Scalable Systems Software Laboratory at Yonsei University advised by prof. Jinkyu Jeong. I received my B.S. degree in the Department of Semi-conductor Systems Engineering at Sungkyunkwan University.

  My research areas encompass operating systems, storage systems, database systems, and performance analysis. I mainly research on system profiling and optimization, especially for heterogeneous computing environments that include emerging hardware devices.
#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sungkyunkwan University
        caption: 2017 - Present
        sub_title: Combined M.S./Ph.D. in Electrical and Computer Engineering
        description: | # this will include new lines to allow paragraphs
          - Proposal: Reserach on Application Performance Profiling Technique in Heterogeneous Computing Environments

          - Advisor: Jinkyu Jeong (in Yonsei University)
      - layout: left
        title: Sungkyunkwan University
        caption: 2013 - 2017
        sub_title: BS in Semiconductor Systems Engineering
        description: | # this will include new lines to allow paragraphs
          - Relevant Courseworks: Operating Systems, Computer Architecture, Multicore Systems, Embedded Systems

          - Graduation project: Implementation of user-level I/O (NVMeDirect) enabled in-memory key-value store
      - layout: left
        title: Korea Science Academy of KAIST (KSA)
        caption: 2010 - 2013
        sub_title: 
        description: | # this will include new lines to allow paragraphs
#In high school, I mainly took courses on object-oriented programming and data structures, while also having a passion for mathematics and physics.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Conference Papers
        caption:
        sub_title:
        description: | # this will include new lines to allow paragraphs
          [OSDI 2024] Minwoo Ahn, Jeongmin Han, Youngjin Kwon, and Jinkyu Jeong, "Identifying On-/Off-CPU Bottlenecks Together with Blocked Samples"

          [USENIX FAST 2021] Jiwon Woo, Minwoo Ahn, Gyusun Lee, and Jinkyu Jeong, "D2FQ: Device-Direct Fair Queueing for NVMe SSDs"
      - layout: top-middle
        title: Journal Papers
        caption:
        sub_title:
        description: | # this will include new lines to allow paragraphs
          Jaehyun Song, Minwoo Ahn, Gyusun Lee, Euiseong Seo, and Jinkyu Jeong, "A Performance-Stable NUMA Management Scheme for Linux-Based HPC Systems," IEEE Access, vol. 9, pp. 52987-53002, March 2021, doi:10.1109/ACCESS.2021.3069991

          Minwoo Ahn, Donghyun Kim, Taekeun Nam, and Jinkyu Jeong, "SCOZ: A System-Wide Causal Profiler for Multicore Systems," Software: Practice and Experience, vol. 51, issue 5, pp. 1043-1058, May 2021, doi:10.1002/spe.2930

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
