# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minwoo Ahn
title: Systems Software Researcher
email: mwahn402@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ski422
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: minwoo-ahn-684b17317
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

## Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
## - title: another link
##   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
##   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. candidate in the Department of Electrical and Computer Engineering at Sungkyunkwan University and also a member of Scalable Systems Software Laboratory at Yonsei University advised by prof. Jinkyu Jeong. I received my B.S. degree in the Department of Semi-conductor Systems Engineering at Sungkyunkwan University.

  My research areas encompass operating systems, storage systems, database systems, and performance analysis. I mainly research on system profiling and optimization, especially for heterogeneous computing environments that include emerging hardware devices.

  - Interests - Operating Systems, Storage Systems, Database Systems, Systems for AI, Performance Analysis
  - The PDF version of CV is available at [here](https://drive.google.com/file/d/14L58_zG-H2VN32WhVCSAezAsfaVuX3dw/view?usp=sharing).

content:
  - title: Research Experience
    layout: list
    content:
      - layout: left
        title: Scalable Systems Software Laboratory
        caption: Mar. 2023 - Present
        sub_title: Dispatched Researcher (Advised by Jinkyu Jeong)
        description:
        
      - layout: left
        title: Computer Systems Laboratory
        caption: Mar. 2017 - Feb. 2023
        sub_title: Graduated Researcher (Advised by Jinkyu Jeong)
        description:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sungkyunkwan University
        caption: 2017 - Present
        sub_title: Combined M.S./Ph.D. in Electrical and Computer Engineering
        description: | # this will include new lines to allow paragraphs
          - Proposal: Reserach on Application Performance Profiling Technique in Heterogeneous Computing Environments

          - Advisor: Jinkyu Jeong (in Yonsei University)
      - layout: left
        title: Sungkyunkwan University
        caption: 2013 - 2017
        sub_title: BS in Semiconductor Systems Engineering
        description: | # this will include new lines to allow paragraphs
          - Relevant Courseworks: Operating Systems, Computer Architecture, Multicore Systems, Embedded Systems

          - Graduation project: Implementation of user-level I/O (NVMeDirect) enabled in-memory key-value store
      - layout: left
        title: Korea Science Academy of KAIST (KSA)
        caption: 2010 - 2013
        sub_title: 
        description: | # this will include new lines to allow paragraphs
#In high school, I mainly took courses on object-oriented programming and data structures, while also having a passion for mathematics and physics.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Conference Papers
        caption:
        sub_title:
        description: | # this will include new lines to allow paragraphs
          - [OSDI 2024] Minwoo Ahn, Jeongmin Han, Youngjin Kwon, and Jinkyu Jeong, "Identifying On-/Off-CPU Bottlenecks Together with Blocked Samples"

          - [USENIX FAST 2021] Jiwon Woo, Minwoo Ahn, Gyusun Lee, and Jinkyu Jeong, "D2FQ: Device-Direct Fair Queueing for NVMe SSDs"
      - layout: top-middle
        title: Journal Papers
        caption:
        sub_title:
        description: | # this will include new lines to allow paragraphs
          - Jaehyun Song, Minwoo Ahn, Gyusun Lee, Euiseong Seo, and Jinkyu Jeong, "A Performance-Stable NUMA Management Scheme for Linux-Based HPC Systems," IEEE Access, vol. 9, pp. 52987-53002, March 2021, doi:10.1109/ACCESS.2021.3069991

          - Minwoo Ahn, Donghyun Kim, Taekeun Nam, and Jinkyu Jeong, "SCOZ: A System-Wide Causal Profiler for Multicore Systems," Software: Practice and Experience, vol. 51, issue 5, pp. 1043-1058, May 2021, doi:10.1002/spe.2930

      - layout: top-middle
        title: Domestic Papers (Korean)
        caption:
        sub_title:
        description: | # this will include new lines to allow paragraphs
          - Jeongmin Han, Minwoo Ahn, and Jinkyu Jeong, "Parallel Filter/Index Access for Improving Read Performance of LSM-Tree," KIISE Transactions on Computing Practice (KTCP), Sep. 2023.
            - Invited Paper (Excellent Presentation Award)

          - Sangyoon Kwon, Minwoo Ahn, and Jinkyu Jeong, "GPU Kernel Speedup Predcition using GPU Causal Profiling," Korea Software Congress, Dec. 2022.

          - Jeongmin Han, Minwoo Ahn, and Jinkyu Jeong, "Multi-Level Filter Access in LSM-tree using Asynchronous I/O," Korea Software Congress, Dec. 2022.
            - Excellent Presentation Award

          - Sungyoon Kim, Sungjun Ha, Minwoo Ahn, and Jinkyu Jeong, "I/O Polling Task Placement on Hyperthreading-Enabled Multicore CPU," Korea Computer Congress, July. 2019.
            - Excellent Paper Award


  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        description: | # this will include new lines to allow paragraphs
          - Korea Exascale Application Software Development Environments
            - Keywords: performance profiling, HPC
            - Goal: Performance profiling framework for exa-scale HPC applications.
            - National Research Foundation of Korea (NRF), Nov 2023 - Apr 2028

          - Research of Key-Value Stores for Exa-Scale SSDs
            - Keywords: NoSQL DBMS, storage systems, memory management
            - Goal: Cost-effective memory management of large-scale DBMS with peta-scale SSDs.
            - Samsung Electrocis, Aug 2022 - Jul 2024

          - Causal Profiling for Heterogeneous Systems
            - Keywords: performance profiling, causal profiling, domain-specific accelerators
            - Goal: Developing causal profiler for heterogeneous systems that include SSDs along with GPU and FPGA.
            - National Research Foundation of Korea (NRF)

          - Application's Performance Profiling and Optimization for Next-Generation SSDs
            - Keywords: storage systems, performance profiling, NoSQL DBMS
            - Goal: Performance profiling and optimization of applications with ultra-low latency SSDs.
            - Samsung Electronics, Aug 2020 - Jul 2022

          - High Performance Computing Environment and Storage System
            - Keywords: high-performance computing, OS noise, memory management, CPU scheduling
            - Goal: Light-weighted Linux kernel for heterogeneous high-performance computing.
            - National Research Foundation of Korea (NRF), Mar 2017 - Jun 2021

  - title: Presentations and Invited Talks # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
#link: boringcompany.com
        # link_text: boringcompany.com
#sub_title: Senior Network System Administrator
#caption: November 2017 - Present
#quote: >
#Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          - [Conference Talk, OSDI \'24] "Identifying On-/Off-CPU Bottlenecks Together with Blocked Samples", Jul 2024
          - [Poster Session, OSDI \'24] "Identifying On-/Off-CPU Bottlenecks Together with Blocked Samples", Jul 2024
          - [Workshop, KCC \'24] "Light-weighted Causal Profiler for Exascale Computing", Jun 2024
          - [Invited Talk, KCC \'21] "D2FQ: Device-Direct Fair Queueing for NVMe SSDs", June 2022

  - title: Awards and Honors
    layout: text
    content: |
      - Excellent Poster Prize - Computer Systems Society, 2024
      - Excellent Presentation Prize - Korea Software Congress, 2022
      - Excellent Paper Prize - Korea Software Congress, 2019
      - Grand Prize (2nd place) - Korea Supercomputing Challenge, 2018

  - title: Awards and Honors
    layout: text
    content: |
      - SKKU Scholarship, Mar. 2017 - Feb. 2020
      - Samsung Electronics Scholarship, Mar. 2016 - Feb. 2017
      - Samsung Electronics Scholarship (tuition and fees), Mar. 2013 - Feb. 2017

  - title: Teaching Experiences (TA)
    layout: text
    content: | # this will include new lines to allow paragraphs
      - System Programming Experiment - Introduction of UNIX programming, 2022
      - JAVA Programming Experiment - Basics of object-oriented programming (JAVA), 2022
      - Embedded Systems Design - FTL design in OpenSSD (Jasmine), 2018
      - Embedded Systems Experiment - Android kernel programming (virtual device), 2018, 2019, 2020, 2021
      - Operating Systems - Design of operating systems and exercises with xv6, 2017, 2018
      - Computer Architecture - Design of computer architecture and implementation of MIPS architecture, 2017, 2019, 2020
      - System Software Experiment 3 - Basics of object-oriented programming (C++), 2017, 2018

  - title: Technical Skills
    layout: text
    content: |
      - Languages: C, C++, Java, Python, Kotlin
      - Skills: Linux kernel programming, System profiling (Linux perf, eBPF), android kernel programming, FTL programming


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
